name: 🐛 버그 제보
description: 서비스에서 발견된 버그를 간략히 제보해 주세요
title: "[Bug] "
labels: [Bug]
assignees: []

body:
  - type: textarea
    attributes:
      label: 🧱 어떤 버그가 있나요?
      description: 어떤 버그인지 구체적으로 설명해 주세요.
      placeholder: 예) 무한 스크롤이 작동하지 않음
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
      description: 버그를 보여주는 스크린샷을 첨부해 주세요.
  - type: textarea
    attributes:
      label: 💻 재현 방법
      description: 어떤 파일에서, 어떤 상황에서, 어떤 순서로 발생했는지 알려주세요.
  - type: textarea
    attributes:
      label: 🔍 예상되는 원인은 무엇인가요?
      description: 코드 상 어떤 문제일 가능성이 있는지 자유롭게 작성해주세요.
  - type: markdown
    attributes:
      value: |
        ### ✅ 사용 예시
        게시글 목록 페이지에서 하단으로 스크롤을 내려도 새로운 게시글이 로딩되지 않고, 로딩 스피너만 무한히 표시됩니다.

        **재현 방법**
        - 문제 부분: [src/pages/PostList.vue의 89번째 줄](https://github.com/myorg/myrepo/blob/main/src/pages/PostList.vue#L89)
        - 상황:
          1. 로그인 후 `/posts` 페이지로 이동
          2. 스크롤을 가장 아래까지 내림
          3. 로딩 아이콘이 계속 돌아가지만, 게시글이 추가로 로딩되지 않음

        **예상 원인**
        1. `fetchMorePosts()` 호출 이후 응답 실패 또는 hasMore 조건 잘못 설정
        2. IntersectionObserver 콜백 내부에서 중복 호출 발생 가능
