name: ✨ 기능 요구사항 이슈
description: 새로 추가되길 원하는 기능을 제안해 주세요
title: "[feat] "
labels: [feat]
assignees: []

body:
  - type: textarea
    attributes:
      label: ✨ 해당 기능은 어떠한 세부 기능이 있나요?
      description: 핵심 기능을 세부 항목으로 나눠 적어 주세요.
      placeholder: 예) - 좋아요 버튼, - 북마크 기능
  - type: textarea
    attributes:
      label: 📸 참고할만한 사이트나 사진 (선택사항)
      description: 참고한 서비스나 이미지 링크 등을 붙여 주세요.
