name: ✨ 기능 요구사항 이슈
description: 새로 추가되길 원하는 기능을 제안해 주세요
title: "[feat] "
labels: [feat]
assignees: []

body:
  - type: textarea
    attributes:
      label: ✨ 해당 기능은 어떠한 세부 기능이 있나요?
  - type: textarea
    attributes:
      label: 📸 참고할만한 사이트나 사진 (선택사항)
  - type: markdown
    attributes:
      value: |
        ```
        # 사용예시( 이 코드 블럭 전체를 지워주세요)

        ---
        name: ✨ 기능 요구사항 이슈
        about: 어떠한 기능인지 요약해주세요(명사형)
        title: "[feat] 게시글 북마크 기능"
        labels: feat
        assignees: ''

        ---

        ## ✨ 해당 기능은 어떠한 세부 기능이 있나요?
        - 게시글 카드에 북마크 아이콘(⭐) 버튼 추가
        - 사용자가 북마크 누르면 서버에 해당 게시글이 저장됨
        - 마이페이지에서 내가 북마크한 게시글 목록 확인 가능
        - 로그인하지 않은 경우 북마크 버튼은 비활성화

        ## 📸 참고할만한 사이트나 사진 (선택사항)
        - [Velog 북마크 기능](https://velog.io/)
        - ![북마크 버튼 예시](https://example.com/bookmark_ui.png)
        ```