name: 🧊 비기능적 불충족 문제
description: 성능, 보안, 호환성 등 기능 외 품질 요구사항이 충족되지 않은 문제 제보
title: "[Non-functional] "
labels: [Non-functional]
assignees: []

body:
  - type: dropdown
    attributes:
      label: 🧱 어떤 문제가 있나요?
      options:
        - 🔐 보안 (Security)
        - ⚙️ 신뢰성 (Reliability)
        - 🧩 확장성 (Scalability)
        - 🔄 이식성 (Portability)
  - type: textarea
    attributes:
      label: 상세 설명
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
  - type: textarea
    attributes:
      label: 💻 재현 방법
  - type: textarea
    attributes:
      label: 🔍 예상되는 원인
  - type: markdown
    attributes:
      value: |
        ```
        # 사용예시( 이 코드 블럭 전체를 지워주세요)

        ## 🧱 어떤 문제가 있나요?
        - 🔄 **이식성 (Portability)**  
        - iOS Safari 브라우저에서 회원가입 버튼이 클릭되지 않음. Chrome, Android 브라우저에서는 정상 작동. 브라우저 간 호환성이 부족한 상태.

        ### 📸 스크린샷 (선택사항)
        ![ios-button-fail](https://example.com/screenshot.png)

        ## 💻 재현 방법
        - 문제 부분: [src/components/RegisterForm.vue의 버튼 이벤트 바인딩](https://github.com/myorg/myrepo/blob/main/src/components/RegisterForm.vue#L72)
        - 상황:
          1. iPhone Safari 브라우저에서 회원가입 페이지 진입
          2. 폼 작성 후 "가입하기" 버튼을 터치
          3. 아무 동작도 일어나지 않음

        ## 🔍 예상되는 원인은 무엇인가요?
        1. `@click` 대신 `@touchend` 이벤트가 필요한 환경에서 발생한 호환성 문제
        2. `preventDefault()`로 인해 iOS 터치 이벤트가 제대로 전파되지 않음
        ```
