name: 🧊 비기능적 불충족 문제
description: 성능, 보안, 호환성 등 기능 외 품질 요구사항이 충족되지 않은 문제 제보
title: "[Non-functional] "
labels: [Non-functional]
assignees: []

body:
  - type: dropdown
    attributes:
      label: 🧱 어떤 문제가 있나요?
      options:
        - 🔐 보안 (Security)
        - ⚙️ 신뢰성 (Reliability)
        - 🧩 확장성 (Scalability)
        - 🔄 이식성 (Portability)
  - type: textarea
    attributes:
      label: 상세 설명
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
  - type: textarea
    attributes:
      label: 💻 재현 방법
  - type: textarea
    attributes:
      label: 🔍 예상되는 원인
  - type: markdown
    attributes:
      value: |
        ### ✅ 사용 예시
        - 🔄 이식성 (Portability)  
        - iOS Safari 브라우저에서 회원가입 버튼이 클릭되지 않음. Android에선 정상.

        **예상 원인**
        - `@click` 대신 `@touchend` 이벤트 필요
        - preventDefault()로 인한 터치 이벤트 차단
