name: ⚡️ 성능 저하 문제 제보
description: 속도, 반응성 등 성능 문제를 제보해 주세요
title: "[Performance] "
labels: [Performance]
assignees: []

body:
  - type: textarea
    attributes:
      label: 🧱 어떤 성능 문제가 있나요?
  - type: textarea
    attributes:
      label: ⏳ 어느 만큼의 성능 문제가 있나요?
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
  - type: textarea
    attributes:
      label: 💻 재현 방법
  - type: textarea
    attributes:
      label: 🔍 예상되는 원인
  - type: markdown
    attributes:
      value: |
        ### ✅ 사용 예시
        대시보드 열 때, 차트 데이터 로딩에 7초 이상 걸림

        **결과**
        - 평균 로딩 시간 7.2초 → 기대값 2초 이내
