name: 🧪 리펙토링 제보
description: 기존 코드 구조 개선이 필요한 경우 제보해 주세요
title: "[Refactor] "
labels: [Refactor]
assignees: []

body:
  - type: textarea
    attributes:
      label: 📖 어느 코드에서 리팩토링이 필요한가요?
      description: 링크나 위치 중심으로 알려주세요
  - type: textarea
    attributes:
      label: 💻 현 코드 기술 방법
      description: 현재 코드가 어떤 방식으로 되어있는지
  - type: textarea
    attributes:
      label: 🔍 왜 리팩토링이 필요한가요?
      description: 문제점, 개선 필요성, 코드 예시 등
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
