name: 🧪 리펙토링 제보
description: 기존 코드 구조 개선이 필요한 경우 제보해 주세요
title: "[Refactor] "
labels: [Refactor]
assignees: []

body:
  - type: textarea
    attributes:
      label: 📖 어느 코드에서 리팩토링이 필요한가요?
  - type: textarea
    attributes:
      label: 💻 현 코드 기술 방법
  - type: textarea
    attributes:
      label: 🔍 왜 리팩토링이 필요한가요?
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
  - type: markdown
    attributes:
      value: |
        ```
        # 사용예시( 이 코드 블럭 전체를 지워주세요)

        ## 📖어느 코드에서 리펙토링이 필요한가요?
        [src/pages/Register.vue의 setup 내부 로직](https://github.com/myorg/myrepo/blob/main/src/pages/Register.vue#L60)

        ## 💻 현 코드 기술 방법
        모든 유효성 검사 로직이 `setup()` 안에 하드코딩돼 있어서 보기 힘들고 재사용도 어려움

        ## 🔍 왜 리펙토링이 필요한가요?
        1. 다른 컴포넌트에서도 같은 유효성 검사 로직 반복됨  
          `js
          if (!email.includes('@')) { ... }
          `
        2. 공통 훅(`useValidation`)으로 빼면 유지보수 쉬워짐

        ### 📸 스크린샷 (선택사항)
        [첨부 예정]
        ```