name: 🧪 리펙토링 제보
description: 기존 코드 구조 개선이 필요한 경우 제보해 주세요
title: "[Refactor] "
labels: [Refactor]
assignees: []

body:
  - type: textarea
    attributes:
      label: 📖 어느 코드에서 리팩토링이 필요한가요?
  - type: textarea
    attributes:
      label: 💻 현 코드 기술 방법
  - type: textarea
    attributes:
      label: 🔍 왜 리팩토링이 필요한가요?
  - type: textarea
    attributes:
      label: 📸 스크린샷 (선택사항)
  - type: markdown
    attributes:
      value: |
        ### ✅ 사용 예시
        Register.vue에서 모든 유효성 검사 로직이 setup() 안에 들어 있어 복잡함. useValidation 훅으로 분리 필요.
